# PROJECT
site_name: Mitsuki's Garden
site_url: https://enolag-1231.github.io/
site_author: Mitsuki_G
site_description:
  Welcome to Mitsuki's rabbit hole. 
  This site serves as a personal knowledge base for me to record my thoughts and ideas.
  Feel free to explore and learn alongside me!

# REPOSITORY
repo_name: Mitsuki_G_Git
repo_url: https://github.com/EnolaG-1231/EnolaG-1231.github.io

# COPYRIGHT
copyright: 'Copyright &copy; 2025 ~ now Mitsuki_Lian. All rights reserved.'

# CONFIGURATION
theme:
  name: material
  favicon: static/favicon.png # 网页小图标
  logo: static/logo.png
  language: 'zh'
  features:
    - announce.dismiss # 呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - content.action.edit # 编辑按钮，似乎没啥用
    # - content.action.view # 查看按钮，似乎没啥用
    - content.code.annotate # 代码注释
    - content.code.copy # 代码复制按钮
    - content.tabs.link # 代码块的tab可以直接链接
    - content.tooltips # 工具提示
    # - header.autohide # 自动隐藏标题栏
    - navigation.expand # tab侧边导航栏默认展开
    # - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.path # 导航路径，好像没啥用
    - navigation.sections # 导航栏的section
    - navigation.tabs #顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 上滑出现返回顶部按钮
    - navigation.tracking #导航栏跟踪
    - search.highlight # 搜索高亮
    - search.suggest # 搜索推荐补全单词
    - search.share # 搜索分享
    - toc.follow # 目录跟踪-页面右侧的小目录
    # - toc.integrate # 目录跟踪集成到左侧大目录中
  icon:
    repo: fontawesome/brands/github #右上角仓库图标
    logo: material/rabbit
  
  palette:
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: teal # teal绿、amber黄好看 
      accent: cyan # 链接等可交互原件的高亮色
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font: # 详见font.css
    text: 'LXGW WenKai'
    code: 'Roboto Mono'

# COMPONENTS
plugins:
  - tags
  - offline
  - glightbox:
      touchNavigation: true # 在移动设备上起用触摸/滑动导航
      loop: true # 循环浏览图片
      zoomable: true # 图片缩放
      draggable: true # 拖动切换图片
      auto_caption: true # 显示图片标题
      caption_position: "left"
      effect: fade
      slide_effect: slide
  - document-dates:
      position: bottom # top or bottom
      type: date # Data type: date, datetime, timeago
      date_format: '%Y-%m-%d'
      # time_format: '%H-%M-%S'
      exclude:
        - gallery.md
        - index.md
        - log.md
        - blog/index.md
        - blog/posts/*
        - about/* # Exclude all files in private directory, including subdirectories

  - blog:
      enabled: true
      blog_toc: true # 显示文章摘要
      post_date_format: full # 时间
      draft: true
      draft_if_future_date: true # 自动将具有未来日期的帖子标记为草稿
      post_readtime: true
      post_readtime_words_per_minute: 265 # 计算帖子的阅读时间时读者每分钟预计阅读的字数
      post_url_format: "{date}/{slug}"
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      # categories_toc: true
      # pagination_per_page: 5
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml" # 作者信息
  # - git-revision-date-localized:
  #     type: iso_date
  #     exclude:
  #       - index.md
  #       - waline.md
  # - rss:
  #     match_path: blog/posts/* # (1)!
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags # (2)!
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])' # 分隔符
  - minify: #压缩插件
      minify_html: true
  - encryptcontent:
      threshold_warning_min_entropy: 0 # 防对熵strict警告
      title_prefix: 'Protected'
      summary: 'This content is protected. Please enter the password.'
      placeholder: 'Enter password'
      password_button_text: ' to unlock YOUR content'
      # encryption_summary: "Legal documents require authorization to view."
      encryption_info_message: "Contact the site administrator for access."
      decryption_failure_message: "Incorrect credentials. Please try again."
      # remember_key: true
      password_button: true
      # 以下三项对于自定义主题可以指定自己的css类，但暂时不懂搞
      form_class: 'custom-decrypt-form'
      input_class: 'custom-input-field'
      button_class: 'custom-button primary'
      # 密码管理
      password_inventory:
        guest: "Lian-031231"
        admin: "Lasmiracle-1131"


markdown_extensions: # 根据指定编程语言高亮显示代码，并可以设置代码段标题
  - abbr
  - admonition # 信息块
  - attr_list # 属性列表
  - def_list
  - footnotes # 脚注
  - md_in_html # html中的markdown
  - meta # 支持Markdown文件上方自定义标题标签等
  - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.arithmatex: # latex支持
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret  # 启用：下划线 ^^、上标 ^
  - pymdownx.critic
  - pymdownx.details # 启用：可折叠的 Admonition
  - pymdownx.emoji: # 表情包
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      # options:
        # custom_icons: # 自定义图标集
        # - overrides/.icons
  - pymdownx.highlight: # 代码块高亮
      auto_title: true # 显示编程语言名称
      anchor_linenums: true
      linenums: true # 显示行号
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # 内联语法高亮
  - pymdownx.keys # 启用：键盘键 ++
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: Mitsuki_G
      repo: mkdocs-material
  - pymdownx.mark # 启用：突出显示 == 
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences: # 代码块
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde # 启用：删除线 ~~、下标 ~
  

# navigation
nav:
  - Home: 'index.md'
  - Docs:
    - Note1_Computer: 'doc/n1.md'
    - Note2_Svenska: 'doc/n2.md'
    - about: doc/about.md
  - Blog:
    - blog/index.md
    - about: blog/about.md
  - Gallery: 
    - 'gallery/gallery.md'
  - Logs: 'log.md'

# extra configuration
extra:
  generator: true # 删除页脚显示“使用MkDocs材料制造”
  analytics: # 目前懒得搞google analytics，这块儿暂时没用
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback: # feedback form
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up
          name: This page was helpful
          data: 1
          note: >-
            Thank you for your feedback! 
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by using our
            <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback</a>
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/EnolaG-1231/
  tags: # 自定义标签（？
    Default: default-tag
    Software: software-tag
    Hardware: hardware-tag
  # consent: # 征求同意 Cookie
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
  alternate:
    - name: 中文
      link: "javascript:GLMTranslate.translateTo('chinese_simplified');"
      lang: zh
    - name: English
      link: "javascript:GLMTranslate.translateTo('english');"
      lang: en
    - name: 日本語
      link: "javascript:GLMTranslate.translateTo('japanese');"
      lang: ja



extra_javascript: # 引用自定义 JS 文件
  - javascripts/extra.js 
  # 智谱清言翻译系统
  - javascripts/glm-config.js
  - javascripts/glm-translate.js
  - javascripts/mathjax.js # latex支持
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  # 博客文章标记脚本
  - javascripts/blog-scope.js
  - javascripts/home-greeting.js
  # 鼠标点击特效
  - javascripts/click-effects.js
  - javascripts/md-link-fixer.js # 解决markdown内链接问题


extra_css: # 引用自定义 CSS 文件
  # - stylesheets/link.css
  - stylesheets/font.css  #字体，还没写
  - stylesheets/click-effects.css
  # - stylesheets/extra.css # 固定放最后避免被覆盖。。
  - stylesheets/extra.css
  - stylesheets/extra2.css
  # - stylesheets/extra1.css # 原使用主题配色+背景方案
  - stylesheets/gallery.css
  - stylesheets/home.css
